name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Instala deps y build del FRONT
      - name: Install & build client
        working-directory: clock-weather-client
        run: |
          npm ci
          npm run build

      # Instala deps del SERVER
      - name: Install server deps
        working-directory: server
        run: npm ci

      # Deploy a tu Web App de Azure
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: clock-weather-jose        # <-- cambia por el nombre de tu Web App
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
